const { z } = require('zod');
const financeService = require('../../services/financeService');
const { toMcpToolError } = require('../../utils/agentError');
const { logError, logInfo } = require('../../utils/logger');

const moneyInput = z.union([z.number(), z.string()]);
const positiveIntInput = z.union([z.number().int().positive(), z.string().regex(/^\d+$/)]);
const optionalText = (max = 500) => z.string().max(max).optional();
const workspaceIdInput = {
  workspaceId: optionalText(120).describe('Workspace ID. If omitted and the user has more than one workspace, the tool returns workspace_required and the agent must call list_workspaces first.')
};
const accountSelectorInput = {
  accountId: optionalText(120).describe('Preferred account ID. Use IDs returned by list_accounts.'),
  accountName: optionalText(160).describe('Account name fallback. If ambiguous or not found, call list_accounts or upsert_account before retrying.')
};
const paymentMethodSelectorInput = {
  paymentMethodId: optionalText(120).describe('Preferred payment method ID from list_payment_methods.'),
  paymentMethodName: optionalText(160).describe('Payment method name fallback. If ambiguous or not found, call list_payment_methods or upsert_payment_method before retrying.')
};
const categorySelectorInput = {
  categoryId: optionalText(120).describe('Preferred category ID returned by list_categories. Use this when the user selected an existing category.'),
  categoryName: optionalText(80).describe('Category name fallback. The category must already exist in the workspace. If not found, call list_categories, ask the user to choose an existing category or approve creating a new one with upsert_category, then retry.')
};
const creditSelectorInput = {
  creditId: optionalText(120).describe('Preferred credit ID returned by list_credits. Use this when the credit or financed purchase is already known.'),
  creditName: optionalText(160).describe('Credit name fallback. If ambiguous or not found, call list_credits, show the active credits/financed purchases, ask the user which one they mean, then retry with creditId.')
};
const dateInput = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe('Date in YYYY-MM-DD format. Ask the user if missing or ambiguous.');
const currencyInput = z.string().regex(/^[A-Za-z]{3}$/).default('MXN').describe('ISO 4217 currency code. Defaults to MXN.');
const optionalCurrencyInput = z.string().regex(/^[A-Za-z]{3}$/).optional().describe('ISO 4217 currency code. Omit to keep the existing currency, or default to MXN when creating a new goal.');
const financialGoalTypeInput = z.enum([
  'purchase',
  'savings',
  'debt_payoff',
  'investment',
  'retirement',
  'emergency_fund',
  'education',
  'housing',
  'travel',
  'other'
]);
const financialGoalStatusInput = z.enum(['active', 'paused', 'completed', 'cancelled']);
const financialGoalPriorityInput = z.enum(['low', 'medium', 'high']);
const idempotencyKeyInput = z.string().min(12).max(260).describe('Unique retry key generated by the agent for this exact write, such as expense:2026-06-26:coffee:8f3a21. Include the action, movement date, compact real-world summary, and a random or timestamp suffix. Reuse the same key only when retrying the exact same tool call after a technical failure. Never reuse it for a separate real-world movement, even if amount, account, merchant, and date are similar.');
const repaymentPlanInput = {
  termMonths: positiveIntInput.describe('Exact number of months/installments in the repayment plan. Required for every credit or financed purchase. Ask the user if missing; do not infer it.'),
  firstPaymentDate: dateInput.describe('Exact first payment due date in YYYY-MM-DD format. Ask the user if they only gave a purchase/credit date.'),
  interestType: z.enum(['no_interest', 'msi', 'fixed_total', 'fixed_payment']).describe('Controlled repayment type. Use msi only when the user confirms months without interest and total repayment equals the financed amount. Use no_interest for non-MSI credit without interest. Use fixed_total when the user knows total repayment or total interest. Use fixed_payment when the user knows the exact monthly payment. If interest will be charged, do not use msi/no_interest.'),
  totalRepaymentAmount: moneyInput.optional().describe('Total amount the user will repay over the whole plan. Required for interestType=fixed_total unless interestAmount is provided. Do not estimate it.'),
  monthlyPayment: moneyInput.optional().describe('Exact monthly payment amount. Required for interestType=fixed_payment. Do not calculate it unless the user explicitly provided the exact value.'),
  interestAmount: moneyInput.optional().describe('Total interest or extra cost for the whole plan. Can be 0. Use as an alternative to totalRepaymentAmount for interestType=fixed_total. Ask the user when interest exists and the total repayment is unknown.')
};

const metadataFromAuth = (authContext) => ({
  clientId: authContext.clientId,
  scope: authContext.scope,
  resource: authContext.resource
});

const successResponse = ({ result, text }) => ({
  structuredContent: result,
  content: [
    {
      type: 'text',
      text
    }
  ]
});

const registerFinanceTool = (server, authContext, {
  name,
  config,
  handler,
  successText
}) => {
  server.registerTool(name, config, async (args = {}) => {
    logInfo(`mcp.tool.${name}.start`, {
      userId: authContext.userId,
      clientId: authContext.clientId,
      args
    });

    try {
      const result = await handler(args);

      logInfo(`mcp.tool.${name}.success`, {
        userId: authContext.userId,
        clientId: authContext.clientId,
        workspaceId: result.workspaceId || '',
        documentId: result.documentId || result.movementId || '',
        action: result.action
      });

      return successResponse({
        result,
        text: successText(result)
      });
    } catch (error) {
      logError(`mcp.tool.${name}.error`, error, {
        userId: authContext.userId,
        clientId: authContext.clientId,
        args
      });

      return toMcpToolError(error);
    }
  });
};

const registerFinanceTools = (server, { authContext }) => {
  registerFinanceTool(server, authContext, {
    name: 'upsert_workspace',
    config: {
      title: 'Create or update workspace',
      description: 'Creates or updates a workspace to separate finances. Omit workspaceId to create a new workspace. Provide workspaceId to update name, type, currency, description, or active state. Use personal for one person, household for shared home/family/partner finances, and business for micro-business or company finances.',
      inputSchema: {
        workspaceId: optionalText(120).describe('Workspace ID to update. Omit to create a new workspace.'),
        name: optionalText(160).describe('Workspace name, such as Personal, Home, Family, Consulting, or My Business. Required when creating a workspace. Omit when updating other fields only.'),
        type: z.enum(['personal', 'household', 'business']).optional().describe('Workspace type. Use personal for one person, household for shared home/family finances, and business for micro-business use cases.'),
        currency: optionalCurrencyInput,
        description: optionalText(500),
        active: z.boolean().optional().describe('Use false to deactivate a workspace without deleting its data.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertWorkspace({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Workspace ${result.created ? 'created' : 'updated'}: ${result.workspace?.name || result.workspaceId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_workspaces',
    config: {
      title: 'List workspaces',
      description: 'Lists the workspaces available to the authenticated user. Call this before finance actions when workspaceId is missing and the user may have more than one workspace. Show the options and ask which workspace to use.',
      inputSchema: {},
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: () => financeService.listWorkspaces({
      userId: authContext.userId,
      authContext
    }),
    successText: (result) => `${result.workspaces.length} workspace(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_workspace_member',
    config: {
      title: 'Create or update workspace member',
      description: 'Adds or updates an existing user as a member of a workspace. The member must already have signed in to this MCP with Google at least once, because users are identified by Firebase Auth UID. Prefer memberEmail when the UID is unknown. The user only chooses a role: viewer can use read-only tools, member can read and write finance data but cannot manage members, and admin can use every workspace tool including member management. If the target user is not found, tell them to connect the MCP with Google first, then retry.',
      inputSchema: {
        ...workspaceIdInput,
        memberUserId: optionalText(120).describe('Firebase UID of the user to add. Use only if known.'),
        memberEmail: optionalText(320).describe('Google email used by the member when they signed in to this MCP. Preferred when UID is unknown.'),
        role: z.enum(['viewer', 'member', 'admin']).default('member').describe('Workspace role. viewer = read-only tools. member = read and write finance tools, without member management. admin = all workspace tools, including members.'),
        notes: optionalText(500)
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertWorkspaceMember({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Member ${result.created ? 'added' : 'updated'}: ${result.member?.email || result.memberUserId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_workspace_members',
    config: {
      title: 'List workspace members',
      description: 'Lists members of a workspace and their workspace-level scopes. Use this before adding/updating a member when you need to inspect existing access, or when a tool returns workspace_scope_denied and the user wants to know who has access. If workspaceId is missing and the user has multiple workspaces, call list_workspaces first and ask which workspace to inspect.',
      inputSchema: {
        ...workspaceIdInput,
        includeInactive: z.boolean().default(false).describe('Whether to include inactive members. Defaults to false.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listWorkspaceMembers({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} member(s) in ${result.workspace?.name || result.workspaceId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_financial_goals',
    config: {
      title: 'List financial goals',
      description: 'Lists the financial goals and planning notes saved in a workspace. Use this when the user asks about their goals, before editing a goal when goalId is unknown, and when financial context could affect advice or prioritization. This tool does not read movements or account balances.',
      inputSchema: {
        ...workspaceIdInput,
        type: financialGoalTypeInput.optional().describe('Optional goal type filter. Omit to list all goal types.'),
        status: financialGoalStatusInput.optional().describe('Optional goal status filter. Omit to list every status.'),
        includeInactive: z.boolean().default(false).describe('Whether to include inactive goals. Defaults to false.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listFinancialGoals({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} financial goal(s) found.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_financial_goal',
    config: {
      title: 'Create or update financial goal',
      description: 'Creates or updates a financial goal/context note for the workspace. Use this for user intentions, priorities, milestones, savings targets, retirement targets, planned purchases, debt payoff objectives, or other financial context. This tool never moves money, never changes account balances, and never records a movement. If goalId is unknown and the user wants to edit or rename an existing goal, call list_financial_goals first and retry with goalId. Do not invent amounts, dates, ages, or priorities; save unknown details as omitted and ask follow-up questions only when needed for the user request.',
      inputSchema: {
        ...workspaceIdInput,
        goalId: optionalText(120).describe('Financial goal ID to update. Omit to create a new goal or update by unique normalized name. Use goalId when renaming a goal or when the name could be ambiguous.'),
        name: optionalText(160).describe('Short user-facing goal name. Required when goalId is omitted. If goalId is provided, include name only when renaming the goal.'),
        type: financialGoalTypeInput.optional().describe('Controlled goal type. Use purchase, savings, debt_payoff, investment, retirement, emergency_fund, education, housing, travel, or other. Omit if unclear.'),
        status: financialGoalStatusInput.optional().describe('Goal status. Use active for current goals, paused for intentionally deferred goals, completed when achieved, and cancelled when no longer relevant.'),
        priority: financialGoalPriorityInput.optional().describe('User priority for this goal: low, medium, or high. Omit if the user has not expressed priority.'),
        currency: optionalCurrencyInput,
        targetAmount: moneyInput.optional().describe('Optional target amount needed for the goal. Do not estimate it; ask or omit when unknown.'),
        currentAmount: moneyInput.optional().describe('Optional amount currently accumulated or allocated toward this goal. Do not infer it from balances unless the user explicitly says so.'),
        monthlyContribution: moneyInput.optional().describe('Optional planned recurring contribution toward this goal. Do not calculate or assume it unless the user provided it or explicitly asked you to compute a plan.'),
        targetDate: dateInput.optional().describe('Optional target date in YYYY-MM-DD format. Omit if the goal has no clear date yet.'),
        targetAge: positiveIntInput.optional().describe('Optional target age as a whole number, useful for long-term goals like retirement. Omit if not applicable or unknown.'),
        description: optionalText(1000).describe('Optional plain-language description of the goal.'),
        motivation: optionalText(1000).describe('Optional reason why this goal matters to the user. Useful context for future recommendations.'),
        notes: optionalText(1500).describe('Optional additional notes, assumptions, constraints, or preferences shared by the user.'),
        tags: z.array(z.string().min(1).max(80)).max(20).optional().describe('Optional short labels for grouping goals.'),
        active: z.boolean().optional().describe('Use false to hide/archive the goal without deleting history. Prefer status=completed or cancelled when the user is describing the goal outcome.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertFinancialGoal({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Financial goal ${result.created ? 'created' : 'updated'}: ${result.goal?.name || result.goalId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_categories',
    config: {
      title: 'List categories',
      description: 'Lists the controlled category catalog for a workspace. Use this before upsert_expense or upsert_income when categoryId is unknown, when the user gave a possible category name, or when a movement tool returns category_required/category_not_found/category_type_mismatch. Categories are not free text during movement creation: the agent must use an existing category, or ask the user whether to create a new one with upsert_category. If the list is empty, explain that the workspace has no categories yet and ask what category the user wants to create for this movement.',
      inputSchema: {
        ...workspaceIdInput,
        type: z.enum(['expense', 'income', 'both']).optional().describe('Optional category type filter. Use expense before expenses, income before income, or omit to list all categories. Categories with type=both are returned by expense/income filters.'),
        includeInactive: z.boolean().default(false).describe('Whether to include inactive categories. Defaults to false.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listCategories({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} category(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_category',
    config: {
      title: 'Create or update category',
      description: 'Creates or updates a controlled category in a workspace. Use only after the user has confirmed the category they want. Do not create categories silently to make another tool succeed. Good flow: call list_categories, show matching options, ask the user if they want to use an existing category or create a new one, then call upsert_category only if the user approves creating/updating it. Category names are user-defined catalog labels; category type is controlled and determines whether it can be used for expenses, income, or both.',
      inputSchema: {
        ...workspaceIdInput,
        categoryId: optionalText(120).describe('Category ID to update. Omit to create or update by unique normalized name.'),
        name: z.string().min(1).max(80).describe('Free catalog label chosen by the user, such as Food, Transport, Salary, Sales, Rent, Fees, or Interest. Keep the user wording when reasonable; do not invent broad categories without asking.'),
        type: z.enum(['expense', 'income', 'both']).describe('Controlled category type. Use expense for spending categories, income for income categories, both only when the same category should be valid for expenses and income.'),
        description: optionalText(500).describe('Optional explanation of when to use this category.'),
        active: z.boolean().optional().describe('Use false to deactivate a category without deleting movement history.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertCategory({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Category ${result.category?.name || result.categoryId} listada.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_account',
    config: {
      title: 'Create or update account',
      description: 'Creates or updates a financial account/balance container in a workspace. Public account types are bank, cash, wallet, credit_card, investment, and other. Use credit_card for a real credit card account with its current balance/debt and credit limit when known. Do not use this tool to register a new loan or financed purchase; use create_credit or create_credit_purchase instead. IMPORTANT: Do not create a new account silently just to complete another action. Before creating any new account, ask the user to confirm the necessary setup information, especially current balance. If the user does not know the balance, explain that starting from 0 may make future balances incomplete and ask for confirmation.',
      inputSchema: {
        ...workspaceIdInput,
        accountId: optionalText(120).describe('Account ID to update. Omit to create or update by unique name.'),
        name: z.string().min(1).max(160).describe('Free account display name chosen by the user, such as BBVA, Santander, Cash, Mercado Pago, Main Credit Card, or Investment Account. This is a catalog label, so reuse existing account names when possible.'),
        type: z.enum(['bank', 'cash', 'wallet', 'credit_card', 'investment', 'other']).default('bank').describe('Controlled account type. Use bank for bank accounts, cash for physical cash, wallet for digital wallets, credit_card for credit card balances/debt, investment for investment accounts, and other only when none fits. Do not choose a debt/loan type here; use create_credit/create_credit_purchase for debts with payment schedules.'),
        currency: currencyInput,
        balance: moneyInput.optional().describe('Current account balance. Required when creating a new account. Omit only when updating existing account metadata without changing balance. Positive means money available for normal accounts. For credit_card, this is the current debt/balance owed; the backend stores credit card debt as a negative balance even if the agent sends the debt as a positive amount. Use 0 if nothing is owed. If unsure, ask the user before creating it.'),
        creditLimit: moneyInput.optional().describe('Credit limit for credit_card accounts, when known. Ask for it when the user is setting up a credit card, but do not block setup if the user does not know it.'),
        institution: optionalText(160).describe('Financial institution or provider when applicable, such as BBVA, Santander, Nu, Banamex, Mercado Pago, or GBM. Optional for cash.'),
        description: optionalText(500).describe('Optional notes about what this account represents.'),
        active: z.boolean().optional().describe('Use false to deactivate an account without deleting history.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertAccount({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Cuenta lista: ${result.account?.name || result.accountId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_accounts',
    config: {
      title: 'List accounts',
      description: 'Lists accounts in a workspace. Call this before writing a movement when the account/payment source is unknown. If the list is empty, do not invent an account: ask the user how they paid or where the money came from, then create the needed account with upsert_account only after collecting setup details including current balance. Never guess account IDs when multiple accounts could match.',
      inputSchema: {
        ...workspaceIdInput
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listAccounts({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.accounts.length} cuenta(s) disponibles.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_payment_method',
    config: {
      title: 'Create or update payment method',
      description: 'Creates or updates a payment method inside an account. Payment methods are sub-documents of accounts and must use one of the controlled payment method types. If accountId is unknown, call list_accounts first.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput,
        paymentMethodId: optionalText(120).describe('Payment method ID to update. Omit to create or update by unique name inside the account.'),
        name: z.string().min(1).max(160).describe('Free payment method display name inside the selected account, such as Debit Card, Credit Card, SPEI, Cash, Wallet Balance, or Bank Transfer. This is a catalog label, not a one-off note.'),
        type: z.enum(['debit_card', 'credit_card', 'cash', 'bank_transfer', 'spei', 'wallet_balance', 'other']).default('debit_card').describe('Controlled payment method type. Use debit_card, credit_card, bank_transfer, spei, wallet_balance, cash, or other.'),
        last4: optionalText(4).describe('Last 4 digits, only when known.'),
        network: optionalText(80).describe('Card network or payment network when known, such as Visa, Mastercard, American Express, or SPEI.'),
        description: optionalText(500),
        active: z.boolean().optional()
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertPaymentMethod({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Payment method: ${result.paymentMethod?.name || result.paymentMethodId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_payment_methods',
    config: {
      title: 'List payment methods',
      description: 'Lists payment methods for one account. Call this when the user mentions a card or payment method but the ID is unknown. If accountId is unknown, call list_accounts first.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listPaymentMethods({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.paymentMethods.length} payment method(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_credits',
    config: {
      title: 'List credits',
      description: 'Lists active or historical credits and financed purchases in a workspace. Use this before recording a credit payment when the payment refers to an existing obligation but the creditId is unknown. If includeInstallments=true, the response includes the payment schedule so the agent can identify the next unpaid installment. This tool does not list ordinary expenses or ordinary credit card purchases that were not financed in installments.',
      inputSchema: {
        ...workspaceIdInput,
        status: z.enum(['active', 'paid', 'cancelled']).default('active').describe('Credit status to list. Defaults to active. Use paid/cancelled only when the user asks for historical closed credits.'),
        includeInstallments: z.boolean().default(false).describe('Whether to include installment schedules. Use true before record_credit_payment when the user refers to an installment number or the next payment.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listCredits({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} credit(s) found.`
  });

  registerFinanceTool(server, authContext, {
    name: 'update_credit_metadata_only',
    config: {
      title: 'Update credit metadata only',
      description: 'Updates descriptive metadata for an existing credit or financed purchase. Use this to correct name, provider, description, notes, or active state. This tool does not change principal, amount, term months, interest, payment schedule, installments, payments, account balances, or movements. If the user needs to correct financial amounts or payment history, inspect list_credits/list_movements and ask whether to record an adjustment or create a corrected replacement flow instead of silently editing accounting history.',
      inputSchema: {
        ...workspaceIdInput,
        ...creditSelectorInput,
        name: optionalText(160).describe('New display name for the credit or financed purchase. Omit if unchanged.'),
        provider: optionalText(160).describe('New provider/lender/financing source. Omit if unchanged.'),
        description: optionalText(500).describe('Updated human-readable description. Omit if unchanged.'),
        notes: optionalText(500).describe('Updated notes. Omit if unchanged.'),
        active: z.boolean().optional().describe('Use false to hide/deactivate the credit record without changing accounting history.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.updateCreditMetadataOnly({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Credit metadata updated: ${result.credit?.name || result.creditId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'create_credit',
    config: {
      title: 'Create credit',
      description: 'Registers a cash credit or loan where the user receives money now and owes repayment over time. Use when the financial event is a disbursement of money into one of the user accounts and creates a repayment obligation. Do not use for a purchase paid immediately, and do not use for a purchase to months/installments; use create_credit_purchase for financed purchases. Before calling, collect exact amount received, provider/lender, term months, first payment date, whether interest exists, and either total repayment, total interest, or exact monthly payment when interest exists. Also identify the existing account where the money arrived; if it does not exist, ask for account setup details and create it with upsert_account first. Never assume interest, dates, months, account, or repayment totals.',
      inputSchema: {
        ...workspaceIdInput,
        name: z.string().min(1).max(160).describe('User-facing name for this credit, such as Personal Loan, Payroll Credit, Bank Credit, Store Credit, or Car Loan. Ask if missing.'),
        provider: z.string().min(1).max(160).describe('Who issued the credit or loan, such as a bank, store, fintech, employer, or person. Ask if missing.'),
        amount: moneyInput.describe('Principal amount of money the user received. This is not the total repayment if interest exists. Ask for the exact amount.'),
        currency: currencyInput,
        startDate: dateInput.describe('Date when the credit was received/started in YYYY-MM-DD format.'),
        disbursementAccountId: optionalText(120).describe('Account ID where the borrowed money was deposited or received. Prefer IDs from list_accounts. Required through this or disbursementAccountName.'),
        disbursementAccountName: optionalText(160).describe('Account name where the borrowed money was deposited or received. If unknown, call list_accounts and ask the user.'),
        ...repaymentPlanInput,
        description: optionalText(500).describe('Optional human-readable description of the credit.'),
        notes: optionalText(500).describe('Optional extra notes from the user.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createCredit({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Credit registered with ID ${result.creditId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'create_credit_purchase',
    config: {
      title: 'Create financed purchase',
      description: 'Registers a purchase that will be paid over time through MSI, installments, store financing, or a card installment plan. Use when the financial event is a purchase plus a repayment schedule. Do not use for ordinary purchases paid immediately, even if paid with a credit card; those are upsert_expense. Before calling, collect exact purchase amount, merchant, category, date, term months, first payment date, and whether there is interest. If interest exists, collect exact total repayment, total interest, or exact monthly payment. If it was charged to a registered credit card, identify that credit_card account. If it was financed by a provider outside a registered card, collect provider. Never assume a purchase is cash, card, MSI, interest-free, or interest-bearing without the user saying so.',
      inputSchema: {
        ...workspaceIdInput,
        name: z.string().min(1).max(160).describe('User-facing name for the financed purchase, such as Phone, Laptop, Refrigerator, Motorcycle, Furniture, or Dental Treatment. Ask if missing.'),
        amount: moneyInput.describe('Original purchase amount financed. This is not total repayment if interest exists. Ask for the exact amount.'),
        merchant: z.string().min(1).max(160).describe('Store or merchant where the financed purchase happened. Ask if missing.'),
        ...categorySelectorInput,
        date: dateInput.describe('Purchase date in YYYY-MM-DD format.'),
        currency: currencyInput,
        creditAccountId: optionalText(120).describe('Existing credit_card account ID used for this financed purchase. Prefer IDs from list_accounts. Required through this or creditAccountName when the purchase was made on a registered credit card.'),
        creditAccountName: optionalText(160).describe('Existing credit_card account name used for this financed purchase. If unknown, call list_accounts and ask the user which credit card was used.'),
        provider: optionalText(160).describe('Financing provider when the purchase is not linked to a registered credit card, such as a store, bank, fintech, or lender. Required if creditAccountId/creditAccountName is omitted.'),
        ...repaymentPlanInput,
        description: optionalText(500).describe('Optional human-readable description of the financed purchase.'),
        notes: optionalText(500).describe('Optional extra notes from the user.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createCreditPurchase({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Financed purchase registered with credit ID ${result.creditId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'record_credit_payment',
    config: {
      title: 'Record credit payment',
      description: 'Records a payment toward an existing credit or financed purchase created with create_credit or create_credit_purchase. Use when the payment belongs to a specific registered repayment obligation. First identify the credit with list_credits if creditId is unknown. If the credit is MSI/no_interest, the scheduled installment can be paid without interest breakdown unless the user mentions fees or extra charges. If the credit has interest, or the payment is minimum/partial and tied to this registered credit, collect the exact breakdown: amount paid, interest charged, fees charged, and principal reduction or remaining principal. Do not guess interest or principal. For a general credit card payment not tied to a registered financed purchase/credit plan, use upsert_transfer for the card payment and record any interest/fees separately as an expense after asking the user.',
      inputSchema: {
        ...workspaceIdInput,
        ...creditSelectorInput,
        installmentNumber: positiveIntInput.optional().describe('Specific installment number paid. Omit to use the next unpaid installment when that is what the user means.'),
        date: dateInput.describe('Actual date when the payment was made in YYYY-MM-DD format. This is paidDate for the installment/payment movement, not the installment dueDate. Do not use the due date unless the user says they actually paid on that date.'),
        amount: moneyInput.optional().describe('Total amount paid. If omitted and the selected installment has a scheduled payment, the scheduled amount is used. Ask if the payment was partial, extra, minimum, or otherwise different from the scheduled amount.'),
        paymentAccountId: optionalText(120).describe('Account ID from which the payment money came. Prefer IDs from list_accounts. Required through this or paymentAccountName.'),
        paymentAccountName: optionalText(160).describe('Account name from which the payment money came. If unknown, call list_accounts and ask the user.'),
        principalAmount: moneyInput.optional().describe('Amount of this payment that reduced the outstanding principal/debt. Required for interest-bearing credits unless remainingPrincipalAfterPayment or interestAmount lets the backend derive it. Do not guess.'),
        interestAmount: moneyInput.optional().describe('Interest charged/paid in this payment. Required for interest-bearing credits unless principalAmount or remainingPrincipalAfterPayment lets the backend derive it. Can be 0. Ask the user when unclear.'),
        feeAmount: moneyInput.optional().describe('Fees/commissions/late charges paid with this payment. Use 0 or omit only when the user did not have fees. Ask if the user mentions minimum payment, late payment, or charges.'),
        remainingPrincipalAfterPayment: moneyInput.optional().describe('Remaining principal/debt after the payment. Use this when the user knows the new outstanding balance instead of the principal/interest split. Do not estimate it.'),
        description: optionalText(500).describe('Optional human-readable payment description.'),
        notes: optionalText(500).describe('Optional extra notes from the user.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.recordCreditPayment({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Credit payment registered with movement ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'void_credit',
    config: {
      title: 'Void credit',
      description: 'Voids a cash credit/loan created with create_credit by creating an auditable reversal movement, cancelling the credit, voiding its original disbursement movement, voiding its unpaid installment schedule, and reversing affected account balances. Use only when the credit/loan was registered by mistake or must be cancelled as if it should not remain active. This tool does not physically delete data. If the credit has active payments, this tool returns credit_has_active_payments; the agent must void those payments first with void_credit_payment, then retry. Do not use for financed purchases/MSI; use void_credit_purchase.',
      inputSchema: {
        ...workspaceIdInput,
        ...creditSelectorInput,
        date: dateInput.describe('Date of the void/reversal in YYYY-MM-DD format. Ask the user if the correction date is unclear.'),
        reason: z.string().min(1).max(500).describe('Required audit reason explaining why this credit is being voided. Ask the user before calling.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.voidCredit({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Credit voided with reversal movement ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'void_credit_purchase',
    config: {
      title: 'Void financed purchase',
      description: 'Voids a financed purchase, MSI purchase, or installment purchase created with create_credit_purchase by creating an auditable reversal movement, cancelling the financed purchase, voiding its original purchase movement, voiding its unpaid installment schedule, and reversing affected debt/account balances. Use only when the financed purchase was registered by mistake or must be cancelled as if it should not remain active. This tool does not physically delete data. If the financed purchase has active payments, this tool returns credit_has_active_payments; the agent must void those payments first with void_credit_payment, then retry. Do not use for cash credits/loans where the user received money; use void_credit.',
      inputSchema: {
        ...workspaceIdInput,
        ...creditSelectorInput,
        date: dateInput.describe('Date of the void/reversal in YYYY-MM-DD format. Ask the user if the correction date is unclear.'),
        reason: z.string().min(1).max(500).describe('Required audit reason explaining why this financed purchase is being voided. Ask the user before calling.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.voidCreditPurchase({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Financed purchase voided with reversal movement ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'void_credit_payment',
    config: {
      title: 'Void credit payment',
      description: 'Voids a credit payment movement created with record_credit_payment by creating an auditable reversal movement, marking the original payment as voided, reversing account balances, restoring outstanding principal, and updating the related installment/payment totals. Use this when a credit payment was recorded by mistake or needs to be corrected. This tool does not physically delete data. After voiding a wrong payment, call record_credit_payment again only if the user confirms the corrected payment details. The agent should call list_movements with type=credit_payment when paymentMovementId is unknown.',
      inputSchema: {
        ...workspaceIdInput,
        paymentMovementId: z.string().min(1).max(120).describe('Movement ID of the credit_payment to void. Use IDs returned by list_movements with type=credit_payment.'),
        date: dateInput.describe('Date of the void/reversal in YYYY-MM-DD format. Ask the user if the correction date is unclear.'),
        reason: z.string().min(1).max(500).describe('Required audit reason explaining why this payment is being voided. Ask the user before calling.'),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.voidCreditPayment({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Credit payment voided with reversal movement ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_expense',
    config: {
      title: 'Create or update expense',
      description: 'Creates or fully replaces an ordinary expense paid immediately and updates account balances. Omit movementId to create. Provide movementId to update an existing expense; updates require the full corrected expense details, not only the changed field, so balances can be reversed and reapplied safely. Use this for cash, debit, wallet, transfer, and ordinary credit card purchases that are not financed in months/installments. Do not use this when the purchase has a repayment term, installment schedule, MSI plan, financing provider, or deferred payment obligation; use create_credit_purchase instead. Identify/ask all required information, including how the user paid, merchant, category, date, amount, and account. Before calling it, use list_categories when the category is unknown or not confirmed; if the needed category does not exist, ask whether to create it and call upsert_category first. If the account does not exist, do not auto-create it; ask for setup details including current balance and call upsert_account. Always give the user a brief summary before writing.',
      inputSchema: {
        ...workspaceIdInput,
        movementId: optionalText(120).describe('Existing expense movement ID to update. Omit to create a new expense. Use IDs returned by list_movements.'),
        amount: moneyInput.describe('Expense amount as a positive number.'),
        merchant: z.string().min(1).max(160).describe('Merchant/place where the expense happened. If the place is missing or ambiguous, ask before calling unless the user explicitly accepts an unspecified merchant.'),
        ...categorySelectorInput,
        date: dateInput,
        currency: currencyInput,
        ...accountSelectorInput,
        ...paymentMethodSelectorInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertExpense({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Expense ${result.created === false ? 'updated' : 'registered'} with ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_income',
    config: {
      title: 'Create or update income',
      description: 'Creates or fully replaces income and updates account balances. Omit movementId to create. Provide movementId to update an existing income movement; updates require the full corrected income details, not only the changed field, so balances can be reversed and reapplied safely. Before calling it, use list_categories when the category is unknown or not confirmed; if the needed category does not exist, ask the user whether to create it and call upsert_category first. Identify where the money entered: cash, bank, wallet, etc. If the destination account is unknown or does not exist, ask for account setup details including current balance and create it with upsert_account before recording income. Ask for missing source/account details before calling and summarize what will be recorded.',
      inputSchema: {
        ...workspaceIdInput,
        movementId: optionalText(120).describe('Existing income movement ID to update. Omit to create a new income movement. Use IDs returned by list_movements.'),
        amount: moneyInput.describe('Income amount as a positive number.'),
        sourceName: optionalText(160).describe('Income source, such as employer, client, refund, sale, interest, or gift. Ask if the source matters for the user and is missing.'),
        ...categorySelectorInput,
        date: dateInput,
        currency: currencyInput,
        ...accountSelectorInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertIncome({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Income ${result.created === false ? 'updated' : 'registered'} with ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_transfer',
    config: {
      title: 'Create or update transfer',
      description: 'Creates or fully replaces a money transfer between two existing accounts and updates both balances. Omit movementId to create. Provide movementId to update an existing transfer; updates require the full corrected transfer details, not only the changed field, so balances can be reversed and reapplied safely. Use for bank-to-wallet transfers, ATM withdrawals, and general credit card payments that are not tied to a registered credit/installment plan. For ATM withdrawal, model it as fromAccount=bank and toAccount=cash. For paying a credit card balance, model it as fromAccount=bank/cash/wallet and toAccount=credit_card. If the payment includes interest, fees, or minimum-payment charges, ask the user for the exact interest/fee amounts and record those charges separately as expenses; do not hide them inside the transfer. If the payment is for a specific credit or financed purchase registered by create_credit/create_credit_purchase, use record_credit_payment instead. If either account is missing, do not create it silently; ask for account setup details including current balance and create it with upsert_account first. Never use the same account as origin and destination. Summarize the origin, destination, amount, and meaning before writing.',
      inputSchema: {
        ...workspaceIdInput,
        movementId: optionalText(120).describe('Existing transfer movement ID to update. Omit to create a new transfer. Use IDs returned by list_movements.'),
        amount: moneyInput.describe('Transfer amount as a positive number.'),
        date: dateInput,
        currency: currencyInput,
        fromAccountId: optionalText(120).describe('Origin account ID.'),
        fromAccountName: optionalText(160).describe('Origin account name fallback.'),
        toAccountId: optionalText(120).describe('Destination account ID.'),
        toAccountName: optionalText(160).describe('Destination account name fallback.'),
        category: optionalText(80).describe('Optional internal transfer label. Defaults to transfer. This is not an expense/income category and does not require upsert_category.'),
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertTransfer({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Transfer ${result.created === false ? 'updated' : 'registered'} with ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'set_account_balance',
    config: {
      title: 'Set account balance',
      description: 'Sets an account balance to an exact amount and records a balance_adjustment movement for auditability. Use this when the user says the current balance of an account. If account is unknown, call list_accounts first. This changes the account balance by the difference between current and target balance.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput,
        balance: moneyInput.describe('Target account balance. Positive means money available for normal accounts. For credit_card, this is the target debt/balance owed; the backend stores credit card debt as a negative balance even if the agent sends the debt as a positive amount.'),
        currency: z.string().regex(/^[A-Za-z]{3}$/).optional().describe('Optional currency. If provided, it must match the account currency.'),
        date: dateInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.setAccountBalance({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Balance updated with movement ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_movements',
    config: {
      title: 'List movements',
      description: 'Lists one page of financial movements for a workspace and date range. Use this for monthly, weekly, daily, annual, or custom queries. If workspaceId is missing and there are multiple workspaces, call list_workspaces first. Use accountId/accountName, type, categoryId, and categoryName filters when needed. The response includes pagination.hasMore and pagination.nextCursor; if hasMore is true, tell the user there are more movements and ask whether they want to see the next page. To continue, call list_movements again with the same filters and cursor=nextCursor.',
      inputSchema: {
        ...workspaceIdInput,
        period: z.enum(['today', 'week', 'month', 'year', 'custom']).default('month').describe('Date period to query. For custom, provide startDate and endDate.'),
        referenceDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('Reference date for today/week/month/year. Use current user-relevant date when possible.'),
        startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        type: z.enum(['expense', 'income', 'transfer', 'balance_adjustment', 'credit_disbursement', 'credit_purchase', 'credit_payment', 'credit_disbursement_void', 'credit_purchase_void', 'credit_payment_void']).optional(),
        accountId: optionalText(120),
        accountName: optionalText(160),
        categoryId: optionalText(120).describe('Optional category ID filter for expense/income movements. Prefer IDs from list_categories.'),
        categoryName: optionalText(80).describe('Optional category name filter. This matches the stored categoryName/category label.'),
        cursor: optionalText(1000).describe('Pagination cursor returned by the previous list_movements response as pagination.nextCursor. Omit for the first page.'),
        limit: z.number().int().min(1).max(100).default(50)
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listMovements({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => result.pagination?.hasMore
      ? `${result.count} movements found. More movements are available; ask the user if they want to see the next page.`
      : `${result.count} movements found. No more movements are available for these filters.`
  });
};

module.exports = {
  registerFinanceTools
};
