const { z } = require('zod');
const financeService = require('../services/financeService');
const { toMcpToolError } = require('../utils/agentError');
const { logError, logInfo } = require('../utils/logger');

const moneyInput = z.union([z.number(), z.string()]);
const optionalText = (max = 500) => z.string().max(max).optional();
const workspaceIdInput = {
  workspaceId: optionalText(120).describe('Workspace ID. If omitted and the user has more than one workspace, the tool returns workspace_required and the agent must call list_workspaces first.')
};
const accountSelectorInput = {
  accountId: optionalText(120).describe('Preferred account ID. Use IDs returned by list_accounts.'),
  accountName: optionalText(160).describe('Account name fallback. If ambiguous or not found, call list_accounts or upsert_account before retrying.')
};
const paymentMethodSelectorInput = {
  paymentMethodId: optionalText(120).describe('Preferred payment method ID from list_payment_methods.'),
  paymentMethodName: optionalText(160).describe('Payment method name fallback. If ambiguous or not found, call list_payment_methods or upsert_payment_method before retrying.')
};
const categorySelectorInput = {
  categoryId: optionalText(120).describe('Preferred category ID returned by list_categories. Use this when the user selected an existing category.'),
  categoryName: optionalText(80).describe('Category name fallback. The category must already exist in the workspace. If not found, call list_categories, ask the user to choose an existing category or approve creating a new one with upsert_category, then retry.')
};
const dateInput = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe('Date in YYYY-MM-DD format. Ask the user if missing or ambiguous.');
const currencyInput = z.string().regex(/^[A-Za-z]{3}$/).default('MXN').describe('ISO 4217 currency code. Defaults to MXN.');
const idempotencyKeyInput = z.string().min(12).max(260).describe('Unique retry key generated by the agent for this exact write. Use action + movement date + a compact summary + random/timestamp suffix, for example expense:2026-06-26:oxxo-cafe:8f3a21. Reuse the same key only when retrying the exact same tool call after a technical failure. Never reuse it for a separate real-world movement, even if amount, account, merchant, and date are similar.');

const metadataFromAuth = (authContext) => ({
  clientId: authContext.clientId,
  scope: authContext.scope,
  resource: authContext.resource
});

const successResponse = ({ result, text }) => ({
  structuredContent: result,
  content: [
    {
      type: 'text',
      text
    }
  ]
});

const registerFinanceTool = (server, authContext, {
  name,
  config,
  handler,
  successText
}) => {
  server.registerTool(name, config, async (args = {}) => {
    logInfo(`mcp.tool.${name}.start`, {
      userId: authContext.userId,
      clientId: authContext.clientId,
      args
    });

    try {
      const result = await handler(args);

      logInfo(`mcp.tool.${name}.success`, {
        userId: authContext.userId,
        clientId: authContext.clientId,
        workspaceId: result.workspaceId || '',
        documentId: result.documentId || result.movementId || '',
        action: result.action
      });

      return successResponse({
        result,
        text: successText(result)
      });
    } catch (error) {
      logError(`mcp.tool.${name}.error`, error, {
        userId: authContext.userId,
        clientId: authContext.clientId,
        args
      });

      return toMcpToolError(error);
    }
  });
};

const registerFinanceTools = (server, { authContext }) => {
  registerFinanceTool(server, authContext, {
    name: 'create_workspace',
    config: {
      title: 'Create workspace',
      description: 'Creates a workspace to separate finances. Use personal for one person, household for shared home/family/partner finances, and business for micro-business or company finances. After creating it, use the returned workspaceId in finance tools.',
      inputSchema: {
        name: z.string().min(1).max(160).describe('Workspace name, such as Personal, Home, Family, Consulting, or My Business.'),
        type: z.enum(['personal', 'household', 'business']).default('personal').describe('Workspace type. Use personal for one person, household for shared home/family finances, and business for micro-business use cases.'),
        currency: currencyInput,
        description: optionalText(500)
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createWorkspace({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Workspace created: ${result.workspace?.name || result.workspaceId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_workspaces',
    config: {
      title: 'List workspaces',
      description: 'Lists the workspaces available to the authenticated user. Call this before finance actions when workspaceId is missing and the user may have more than one workspace. Show the options and ask which workspace to use.',
      inputSchema: {},
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: () => financeService.listWorkspaces({
      userId: authContext.userId,
      authContext
    }),
    successText: (result) => `${result.workspaces.length} workspace(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'add_workspace_member',
    config: {
      title: 'Add workspace member',
      description: 'Adds or updates an existing user as a member of a workspace. The member must already have signed in to this MCP with Google at least once, because users are identified by Firebase Auth UID. Prefer memberEmail when the UID is unknown. The user only chooses a role: viewer can use read-only tools, member can read and write finance data but cannot manage members, and admin can use every workspace tool including member management. If the target user is not found, tell them to connect the MCP with Google first, then retry.',
      inputSchema: {
        ...workspaceIdInput,
        memberUserId: optionalText(120).describe('Firebase UID of the user to add. Use only if known.'),
        memberEmail: optionalText(320).describe('Google email used by the member when they signed in to this MCP. Preferred when UID is unknown.'),
        role: z.enum(['viewer', 'member', 'admin']).default('member').describe('Workspace role. viewer = read-only tools. member = read and write finance tools, without member management. admin = all workspace tools, including members.'),
        notes: optionalText(500)
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.addWorkspaceMember({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Member ${result.created ? 'added' : 'updated'}: ${result.member?.email || result.memberUserId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_workspace_members',
    config: {
      title: 'List workspace members',
      description: 'Lists members of a workspace and their workspace-level scopes. Use this before adding/updating a member when you need to inspect existing access, or when a tool returns workspace_scope_denied and the user wants to know who has access. If workspaceId is missing and the user has multiple workspaces, call list_workspaces first and ask which workspace to inspect.',
      inputSchema: {
        ...workspaceIdInput,
        includeInactive: z.boolean().default(false).describe('Whether to include inactive members. Defaults to false.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listWorkspaceMembers({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} member(s) in ${result.workspace?.name || result.workspaceId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_categories',
    config: {
      title: 'List categories',
      description: 'Lists the controlled category catalog for a workspace. Use this before create_expense or create_income when categoryId is unknown, when the user gave a possible category name, or when a movement tool returns category_required/category_not_found/category_type_mismatch. Categories are not free text during movement creation: the agent must use an existing category, or ask the user whether to create a new one with upsert_category. If the list is empty, explain that the workspace has no categories yet and ask what category the user wants to create for this movement.',
      inputSchema: {
        ...workspaceIdInput,
        type: z.enum(['expense', 'income', 'both']).optional().describe('Optional category type filter. Use expense before expenses, income before income, or omit to list all categories. Categories with type=both are returned by expense/income filters.'),
        includeInactive: z.boolean().default(false).describe('Whether to include inactive categories. Defaults to false.')
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listCategories({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} category(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_category',
    config: {
      title: 'Create or update category',
      description: 'Creates or updates a controlled category in a workspace. Use only after the user has confirmed the category they want. Do not create categories silently to make another tool succeed. Good flow: call list_categories, show matching options, ask the user if they want to use an existing category or create a new one, then call upsert_category only if the user approves creating/updating it. Category names are user-defined catalog labels; category type is controlled and determines whether it can be used for expenses, income, or both.',
      inputSchema: {
        ...workspaceIdInput,
        categoryId: optionalText(120).describe('Category ID to update. Omit to create or update by unique normalized name.'),
        name: z.string().min(1).max(80).describe('Free catalog label chosen by the user, such as food, transport, salary, sales, rent. Keep the user wording when reasonable; do not invent broad categories without asking.'),
        type: z.enum(['expense', 'income', 'both']).describe('Controlled category type. Use expense for spending categories, income for income categories, both only when the same category should be valid for expenses and income.'),
        description: optionalText(500).describe('Optional explanation of when to use this category.'),
        active: z.boolean().optional().describe('Use false to deactivate a category without deleting movement history.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertCategory({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Category ${result.category?.name || result.categoryId} listada.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_account',
    config: {
      title: 'Create or update account',
      description: 'Creates or updates a financial account/balance container in a workspace. Accounts represent where money lives or debt is tracked: bank account, cash, wallet, credit card, investment, loan, or other. IMPORTANT: Do not create a new account silently just to complete another action. Before creating any new account, ask the user to confirm the necessary information (e.g how much money is in the account). For some accounts is important to know the institution (e.g. BBVA, Santander, etc.). Only If the user does not know the balance, let them know that the balance will be set to 0.',
      inputSchema: {
        ...workspaceIdInput,
        accountId: optionalText(120).describe('Account ID to update. Omit to create or update by unique name.'),
        name: z.string().min(1).max(160).describe('Free account display name chosen by the user, such as BBVA, Santander, Efectivo, BBVA Credit, CETES, etc. This is a catalog label, so reuse existing account names when possible.'),
        type: z.enum(['bank', 'cash', 'wallet', 'credit_card', 'investment', 'loan', 'other']).default('bank').describe('Controlled account type. Use bank for bank accounts, cash for physical cash, wallet for digital wallets, credit_card for credit card balances/debt, investment for investment accounts, loan for debts/loans, and other only when none fits.'),
        currency: currencyInput,
        balance: moneyInput.optional().describe('Current account balance. Required when creating a new account. Omit only when updating an existing account metadata without changing balance. Positive means money available; negative can represent debt for credit cards or loans.'),
        institution: optionalText(160).describe('Financial institution or provider when applicable, such as BBVA, Nu, Santander, Banamex, etc. Optional for cash.'),
        description: optionalText(500).describe('Optional notes about what this account represents.'),
        active: z.boolean().optional().describe('Use false to deactivate an account without deleting history.')
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertAccount({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Cuenta lista: ${result.account?.name || result.accountId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_accounts',
    config: {
      title: 'List accounts',
      description: 'Lists accounts in a workspace. Call this before writing a movement when the account/payment source is unknown. If the list is empty, do not invent an account: ask the user how they paid or where the money came from, then create the needed account with upsert_account only after collecting setup details including current balance. Never guess account IDs when multiple accounts could match.',
      inputSchema: {
        ...workspaceIdInput
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listAccounts({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.accounts.length} cuenta(s) disponibles.`
  });

  registerFinanceTool(server, authContext, {
    name: 'upsert_payment_method',
    config: {
      title: 'Create or update payment method',
      description: 'Creates or updates a payment method inside an account. Payment methods are sub-documents of accounts, such as debit card, credit card, bank transfer, SPEI, cash, or wallet balance. If accountId is unknown, call list_accounts first.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput,
        paymentMethodId: optionalText(120).describe('Payment method ID to update. Omit to create or update by unique name inside the account.'),
        name: z.string().min(1).max(160).describe('Free payment method display name inside the selected account, such as Debito BBVA, Credito BBVA, SPEI, etc. This is a catalog label, not a one-off note.'),
        type: z.enum(['debit_card', 'credit_card', 'cash', 'bank_transfer', 'spei', 'wallet_balance', 'other']).default('debit_card').describe('Controlled payment method type. Use debit_card, credit_card, bank_transfer, spei, wallet_balance, cash, or other.'),
        last4: optionalText(4).describe('Last 4 digits, only when known.'),
        network: optionalText(80).describe('Card network or payment network, such as Visa, Mastercard, or SPEI.'),
        description: optionalText(500),
        active: z.boolean().optional()
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.upsertPaymentMethod({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `Payment method: ${result.paymentMethod?.name || result.paymentMethodId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_payment_methods',
    config: {
      title: 'List payment methods',
      description: 'Lists payment methods for one account. Call this when the user mentions a card or payment method but the ID is unknown. If accountId is unknown, call list_accounts first.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listPaymentMethods({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.paymentMethods.length} payment method(s) available.`
  });

  registerFinanceTool(server, authContext, {
    name: 'create_expense',
    config: {
      title: 'Create expense',
      description: 'Registers an expense and subtracts it from the selected account balance;  Identify/ask all required information, such as how the user paid: cash, bank debit, credit card, wallet, transfer, etc. Before calling it, use list_categories when the category is unknown or not confirmed; if the needed category does not exist, ask the user whether to create it and call upsert_category first. If there are no accounts yet or the needed account does not exist, do not auto-create it; first ask the user for account setup details and call upsert_account. Always give the user a brief summary before writing.',
      inputSchema: {
        ...workspaceIdInput,
        amount: moneyInput.describe('Expense amount as a positive number.'),
        merchant: z.string().min(1).max(160).describe('Merchant/place where the expense happened. If the user says "coffee en OXXO", merchant is OXXO. If the place is missing or ambiguous, ask before calling unless the user explicitly accepts "Not specified".'),
        ...categorySelectorInput,
        date: dateInput,
        currency: currencyInput,
        ...accountSelectorInput,
        ...paymentMethodSelectorInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createExpense({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Expense registered with ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'create_income',
    config: {
      title: 'Create income',
      description: 'Registers income and adds it to the selected account balance. Before calling it, use list_categories when the category is unknown or not confirmed; if the needed category does not exist, ask the user whether to create it and call upsert_category first. Identify where the money entered: cash, bank, wallet, etc. If the destination account is unknown or does not exist, ask for account setup details including current balance and create it with upsert_account before recording income. Ask for missing source/account details before calling and summarize what will be recorded.',
      inputSchema: {
        ...workspaceIdInput,
        amount: moneyInput.describe('Income amount as a positive number.'),
        sourceName: optionalText(160).describe('Income source, such as employer, client, refund, or interest.'),
        ...categorySelectorInput,
        date: dateInput,
        currency: currencyInput,
        ...accountSelectorInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createIncome({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Income registered with ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'create_transfer',
    config: {
      title: 'Create transfer',
      description: 'Moves money between two existing accounts and updates both balances. for example bank-to-wallet transfers and ATM withdrawals. For ATM withdrawal, model it as fromAccount=bank and toAccount=cash. If either account is missing, do not create it silently; ask the user for account setup details including current balance and create it with upsert_account first. Never use the same account as origin and destination. Summarize the origin, destination, amount, and resulting meaning before writing.',
      inputSchema: {
        ...workspaceIdInput,
        amount: moneyInput.describe('Transfer amount as a positive number.'),
        date: dateInput,
        currency: currencyInput,
        fromAccountId: optionalText(120).describe('Origin account ID.'),
        fromAccountName: optionalText(160).describe('Origin account name fallback.'),
        toAccountId: optionalText(120).describe('Destination account ID.'),
        toAccountName: optionalText(160).describe('Destination account name fallback.'),
        category: optionalText(80).describe('Optional internal transfer label. Defaults to transfer. This is not an expense/income category and does not require upsert_category.'),
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.createTransfer({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Transferencia registrada con ID ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'set_account_balance',
    config: {
      title: 'Set account balance',
      description: 'Sets an account balance to an exact amount and records a balance_adjustment movement for auditability. Use this when the user says the current balance of an account. If account is unknown, call list_accounts first. This changes the account balance by the difference between current and target balance.',
      inputSchema: {
        ...workspaceIdInput,
        ...accountSelectorInput,
        balance: moneyInput.describe('Target account balance. Can be negative for debt or credit cards.'),
        currency: z.string().regex(/^[A-Za-z]{3}$/).optional().describe('Optional currency. If provided, it must match the account currency.'),
        date: dateInput,
        description: optionalText(260),
        notes: optionalText(500),
        idempotencyKey: idempotencyKeyInput
      },
      annotations: {
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.setAccountBalance({
      userId: authContext.userId,
      authContext,
      payload: args,
      metadata: metadataFromAuth(authContext)
    }),
    successText: (result) => `Balance updated with movement ${result.movementId}.`
  });

  registerFinanceTool(server, authContext, {
    name: 'list_movements',
    config: {
      title: 'List movements',
      description: 'Lists financial movements for a workspace and date range. Use this for monthly, weekly, daily, annual, or custom queries. If workspaceId is missing and there are multiple workspaces, call list_workspaces first. Use accountId/accountName, type, categoryId, and categoryName filters when needed. Returns movements and summary totals.',
      inputSchema: {
        ...workspaceIdInput,
        period: z.enum(['today', 'week', 'month', 'year', 'custom']).default('month').describe('Date period to query. For custom, provide startDate and endDate.'),
        referenceDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('Reference date for today/week/month/year. Use current user-relevant date when possible.'),
        startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
        type: z.enum(['expense', 'income', 'transfer', 'balance_adjustment']).optional(),
        accountId: optionalText(120),
        accountName: optionalText(160),
        categoryId: optionalText(120).describe('Optional category ID filter for expense/income movements. Prefer IDs from list_categories.'),
        categoryName: optionalText(80).describe('Optional category name filter. This matches the stored categoryName/category label.'),
        limit: z.number().int().min(1).max(100).default(50)
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false
      }
    },
    handler: (args) => financeService.listMovements({
      userId: authContext.userId,
      authContext,
      payload: args
    }),
    successText: (result) => `${result.count} movements found.`
  });
};

module.exports = {
  registerFinanceTools
};
